### ISSUE TITLE
How to generate PFM and mask files?

### ISSUE THREAD

**Issue by EnigmaHong** [tdsuper/SPHORB#3]
I using my own spherical panoramic images to get bad results. I think it's about the  PFM and mask files in the Data folder.
Can you tell me how to generate PFM and mask files? thank!

**Comment by tdsuper** [comment]
@EnigmaHong The provided PFM and mask files are generated for input spherical images with resolution 1280x640. If you want to process spherical images with another resolutions, you should first generate the geodesic grid, then store the coordinates of vertices and pixel interpolation weights in PFM files. Mask files are used to extend boundaries and deal with pentagons.

**Comment by riematrix** [comment]
Hi，
I exported the coordinates from image info pfm files and found the distribution is quite different from geoinfo. Seems that the interpolation parameters brought this difference?

**Comment by riematrix** [comment]
I tried to reproduce the imageinfo from this source code. The image split function applies bilinear interpolation with 4 parameters, including coordinates and 2 interpolation weight. But when we use geodesic grid coordinates to re-generate this info, the splited images are in poor quality. Could you please give some instructions on how to generate the interpolation information?
