### ISSUE TITLE
how to train SFAST

### ISSUE THREAD

**Issue by caoxudong0513** [tdsuper/SPHORB#4]
Hi，
Thank you very much for creating this library.can you tell me how to train SFST?i want to adapt to my own cam.
thanks
![image](https://user-images.githubusercontent.com/24645601/51291621-bd716600-1a42-11e9-89df-80e70029de8a.png)

**Comment by tdsuper** [comment]
The way to train SFAST detector is similar to the way to train FAST detector. More details can be found in the ECCV paper "Machine Learning for High-Speed Corner Detection".
